# Generated by Django 5.2.17 on 2026-09-12 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('junior-high', 'Junior High School'), ('senior-high', 'Senior High School'), ('undergraduate', 'Undergraduate'), ('graduate', 'Graduate')], default='undergraduate', max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]